services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admino
      POSTGRES_DB: eta
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  